IntersectMBO/cardano-addresses

- cardano-addresses.cabal
- src/AddressDerivation.hs
- src/Cardano/AddressDerivation.hs
- stack.yaml
> Add address derivation

- cardano-addresses.cabal
- src/Cardano/AddressDerivation.hs
- src/Cardano/AddressDerivation/Byron.hs
- test/Cardano/AddressDerivation/ByronSpec.hs
- test/Cardano/AddressDerivationSpec.hs
- test/Cardano/MnemonicSpec.hs
- test/Test/Arbitrary.hs
> Add byron address derivation

- .github/workflows/main.yml
- cardano-addresses.cabal
- src/Cardano/AddressDerivation.hs
- src/Cardano/AddressDerivation/Byron.hs
- src/Cardano/AddressDerivation/Icarus.hs
- test/Cardano/AddressDerivation/ByronSpec.hs
- test/Cardano/AddressDerivation/IcarusSpec.hs
- test/Test/Arbitrary.hs
Remark: more tests, especially golden tests will come when Address abstraction is added
> Add icarus impl

- src/Cardano/Address/Style/Shelley.hs
- test/Cardano/Address/Style/ShelleySpec.hs
Issue #16 
1. Introduced `Shelley` key
2. Implemented `GenMasterKey` interface
3. Implemented `Hard/SoftDerivation` interface
4. Added unit tests
> Add shelley key impl part1

- cardano-addresses.cabal
- package.yaml
- src/Cardano/Address.hs
- src/Cardano/Address/Derivation.hs
- src/Cardano/Address/Style/Byron.hs
- src/Cardano/Address/Style/Icarus.hs
- src/Cardano/Address/Style/Shelley.hs
- src/Cardano/Mnemonic.hs
- test/Cardano/Address/Style/IcarusSpec.hs
- test/Cardano/Address/Style/ShelleySpec.hs
- test/Cardano/AddressSpec.hs
- test/Test/Arbitrary.hs
Task : #19 
1. Add payment address impl for Shelley - ie., for enterprise addresses
2. Add example of usage
3. Change SndFactor for Shelley and use ScrubbedBytes.
4. Added XPub to ByteString impl not using chain code and using it
5. Added DelegationAddress interface
6. Added DelegationAddress impl for Shelley
7. Introduce HasNetworkDiscriminant for better dealing with network discriminant in both byron/shelley
8. Added roundtrip tests for Shelley
> Add address impl for shelley

- src/Cardano/Address/Style/Byron.hs
- src/Cardano/Address/Style/Icarus.hs
- src/Cardano/Address/Style/Shelley.hs
1. Revisited ghci usage
2. Added missing docs for Shelley
> correct code snippet and improve on documentation

- cardano-addresses.cabal
- src/Cardano/Address.hs
- src/Cardano/Address/Derivation.hs
- src/Cardano/Address/Style/Jormungandr.hs
- src/Cardano/Address/Style/Shelley.hs
- test/Cardano/Address/Style/JormungandrSpec.hs
- test/Cardano/AddressSpec.hs
- test/Test/Arbitrary.hs
Task:
#24 
Done:
1. Ported all needed interfaces from cardano-wallet
2. Added deriveStakingPrivatekey to DelegationAddress interface
3. Added unit tests
> Port jormungandr style

- test/Cardano/Address/DerivationSpec.hs
https://input-output-hk.github.io/cardano-addresses/haddock/cardano-addresses-1.0.0/Cardano-Address-Derivation.html#t:XPrv
```
Chain Code Invariance
forall xprv. xprvChainCode xprv == xpubChainCode (toXPub xprv)
Public Key Signature
forall xprv msg. verify (toXPub xprv) msg (sign xprv msg) == True
```
> Property tests for XPrv

- cardano-addresses.cabal
- package.yaml
- src/Cardano/Address.hs
- test/Cardano/Address/Style/ShelleySpec.hs
Adding golden tests for a number of interesting situations
> Add test vectors

- cardano-addresses.cabal
- src/Cardano/Address.hs
- src/Cardano/Address/Style/Shelley.hs
- src/Codec/Binary/Encoding.hs
- src/Command.hs
- src/Command/Address.hs
- src/Command/Key.hs
- src/Command/Key/Child.hs
- src/Command/Key/FromRecoveryPhrase.hs
- src/Command/Key/Inspect.hs
- src/Command/Key/Public.hs
- src/Command/RecoveryPhrase.hs
- src/Command/RecoveryPhrase/Generate.hs
- src/Options/Applicative/Derivation.hs
- src/Options/Applicative/Encoding.hs
- src/Options/Applicative/MnemonicSize.hs
- src/Options/Applicative/Style.hs
- test/Cardano/Address/Style/ShelleySpec.hs
- test/Cardano/AddressSpec.hs
- test/Codec/Binary/EncodingSpec.hs
- test/Command/Key/ChildSpec.hs
- test/Command/Key/FromRecoveryPhraseSpec.hs
- test/Command/Key/InspectSpec.hs
- test/Command/Key/PublicSpec.hs
- test/Command/KeySpec.hs
- test/Command/RecoveryPhrase/GenerateSpec.hs
- test/Command/RecoveryPhraseSpec.hs
- test/System/IO/ExtraSpec.hs
- test/Test/Arbitrary.hs
- test/Test/Utils.hs
> Add pointer addresses

- cardano-addresses.cabal
- src/Cardano/Address/Style/Shelley.hs
- src/Codec/Binary/Encoding.hs
- src/Data/Word7.hs
- test/Data/Word7Spec.hs
- test/Test/Arbitrary.hs
Follow-up pointer addresses PR
> Separate word7 module

- Dockerfile
- README.md
- Fixes the Docker entrypoint that was using to the build step dir structure
- Adds documentation to the README for building and running commands using auto-remove containers
- Removes whitespace in README
> Docker entrypoint fix and docs

- command-line/cardano-addresses-cli.cabal
- command-line/lib/Command/Address/Inspect.hs
- command-line/package.yaml
- command-line/test/Command/Address/InspectSpec.hs
- core/cardano-addresses.cabal
- core/lib/Cardano/Address/Errors.hs
- core/lib/Cardano/Address/Style/Byron.hs
- core/lib/Cardano/Address/Style/Icarus.hs
- core/lib/Cardano/Address/Style/Jormungandr.hs
- core/lib/Cardano/Address/Style/Shelley.hs
- core/lib/Cardano/Codec/Cbor.hs
Wrt #46. Easier tracing of error causes.
Run:
Built with:
> Use MonadThrow for inspecting addresses

- README.md
- command-line/lib/Command/Address/Delegation.hs
- command-line/lib/Command/Address/Pointer.hs
- command-line/lib/Command/Address/Reward.hs
- command-line/lib/Options/Applicative/Script.hs
- core/lib/Cardano/Address.hs
- core/lib/Cardano/Address/Derivation.hs
- core/lib/Cardano/Address/Style/Byron.hs
- core/lib/Cardano/Address/Style/Icarus.hs
- core/lib/Cardano/Address/Style/Jormungandr.hs
- core/lib/Cardano/Address/Style/Shelley.hs
- core/test/Cardano/Address/DerivationSpec.hs
- core/test/Cardano/Address/Style/ByronSpec.hs
- core/test/Cardano/Address/Style/IcarusSpec.hs
- core/test/Cardano/Address/Style/JormungandrSpec.hs
- core/test/Cardano/Address/Style/ShelleySpec.hs
- core/test/Cardano/AddressSpec.hs
- core/test/Test/Arbitrary.hs
Not only would this make Duncan happy, but it's also much clearer and aligned with the specs :)
> sed -s /staking/delegation/

- .gitignore
- hie-cabal.yaml
This file is hand-generated because that seems to be the way it's done.
To use it, set up your editor for LSP, and run:
ln -s hie-cabal.yaml hie.yaml
> Add haskell-language-server config

- ChangeLog.md
- command-line/package.yaml
- core/package.yaml
> bump version and ChangeLog to 3.1.0

- .github/workflows/main.yml
- .github/workflows/windows.yml
https://github.com/mstksg/setup-stack/issues/13
> Add workaround to fix CI

- README.md
- command-line/cardano-addresses-cli.cabal
- command-line/lib/Command/Script.hs
- command-line/lib/Command/Script/Hash.hs
- command-line/lib/Command/Script/Validation.hs
- command-line/lib/Options/Applicative/Script.hs
- command-line/lib/System/IO/Extra.hs
- command-line/test/Command/Script/HashSpec.hs
- command-line/test/Command/Script/ValidationSpec.hs
- command-line/test/Command/ScriptSpec.hs
- core/cardano-addresses.cabal
- core/lib/Cardano/Address/Script.hs
- core/lib/Cardano/Address/Script/Parser.hs
- core/package.yaml
- core/test/Cardano/Address/ScriptSpec.hs
ADP-637
Parametrizing Script
Adding Cosigner type
Adding ScriptTemplate type
Adding ToJSON and FromJSON instances of ScriptTemplate
Better error handling
> Introduce script template

- ChangeLog.md
- command-line/cardano-addresses-cli.cabal
- command-line/package.yaml
- core/cardano-addresses.cabal
- core/package.yaml
- 5299d32c44a03d5830bc06bdcdb5c94c0acb2f05
update changelog
- 2bd0df6fec078346c84b561222869418cd06891e
Bump version to 3.2.0
> update changelog and bump version to 3.2.0

- README.md
- command-line/cardano-addresses-cli.cabal
- command-line/lib/Command/Script.hs
- command-line/lib/Command/Script/Preimage.hs
- command-line/test/Command/Script/PreimageSpec.hs
https://jira.iohk.io/browse/SCP-1774
> Add preimage for script

- cabal.project
- core/cardano-addresses.cabal
- nix/haskell.nix
- nix/sources.json
- release.nix
[Hydra jobset PR #106](https://hydra.iohk.io/jobset/Cardano/cardano-addresses-pr-106#tabs-jobs)
> Add ghcjs to CI and fix build issues

- ChangeLog.md
- command-line/cardano-addresses-cli.cabal
- command-line/lib/Command/Address/Bootstrap.hs
- command-line/lib/Command/Key/Child.hs
- command-line/lib/Options/Applicative/Derivation.hs
- command-line/package.yaml
- command-line/test/Test/Utils.hs
- core/cardano-addresses.cabal
- core/lib/Cardano/Address/Derivation.hs
- core/lib/Cardano/Address/Style/Byron.hs
- core/lib/Cardano/Address/Style/Icarus.hs
- core/lib/Cardano/Address/Style/Shelley.hs
- core/package.yaml
- core/test/Cardano/Address/DerivationSpec.hs
- core/test/Cardano/Address/ScriptSpec.hs
- core/test/Cardano/Address/Style/IcarusSpec.hs
- core/test/Cardano/Address/Style/ShelleySpec.hs
- core/test/Test/Arbitrary.hs
- nix/haskell.nix
ADP-699
These are @luite's modifications for 32-bit targets, with some review.
[Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-addresses-pr-112#tabs-jobs)
> Remove Enum instances that don't work on 32-bit targets

- core/lib/Cardano/Address/Style/Shelley.hs
- core/test/golden/addresses_art_forum_devote_street_sure_rather_head_chuckle_guard_poverty_release_quote_oak_craft_enemy/golden
- core/test/golden/addresses_churn_shaft_spoon_second_erode_useless_thrive_burst_group_seed_element_sign_scrub_buffalo_jelly_grace_neck_useless/golden
- core/test/golden/addresses_draft_ability_female_child_jump_maid_roof_hurt_below_live_topple_paper_exclude_ordinary_coach_churn_sunset_emerge_blame_ketchup_much/golden
- core/test/golden/addresses_excess_behave_track_soul_table_wear_ocean_cash_stay_nature_item_turtle_palm_soccer_lunch_horror_start_stumble_month_panic_right_must_lock_dress/golden
- core/test/golden/addresses_test_child_burst_immense_armed_parrot_company_walk_dog/golden
- core/test/golden/addresses_test_walk_nut_penalty_hip_pave_soap_entry_language_right_filter_choice/golden
- core/test/golden/inspectsart_forum_devote_street_sure_rather_head_chuckle_guard_poverty_release_quote_oak_craft_enemy/golden
- core/test/golden/inspectschurn_shaft_spoon_second_erode_useless_thrive_burst_group_seed_element_sign_scrub_buffalo_jelly_grace_neck_useless/golden
- core/test/golden/inspectsdraft_ability_female_child_jump_maid_roof_hurt_below_live_topple_paper_exclude_ordinary_coach_churn_sunset_emerge_blame_ketchup_much/golden
- core/test/golden/inspectsexcess_behave_track_soul_table_wear_ocean_cash_stay_nature_item_turtle_palm_soccer_lunch_horror_start_stumble_month_panic_right_must_lock_dress/golden
- core/test/golden/inspectstest_child_burst_immense_armed_parrot_company_walk_dog/golden
- core/test/golden/inspectstest_walk_nut_penalty_hip_pave_soap_entry_language_right_filter_choice/golden
ADP-744
Spending key hash should have HRP `addr_vkh`.
> Fix inspectAddress spending_key_hash_bech32

- core/lib/Cardano/Address/Script.hs
- core/test/Cardano/Address/ScriptSpec.hs
adp-934
Expose script validation in script template to be used in cardano-addresses
> Add script validation for script template

- command-line/cardano-addresses-cli.cabal
- command-line/package.yaml
- core/cardano-addresses.cabal
- core/lib/Cardano/Address/Script.hs
- core/package.yaml
- core/test/Cardano/Address/ScriptSpec.hs
adp-934
Improve on errors when validation a script template
needed in this PR https://github.com/input-output-hk/cardano-wallet/pull/2663
> Add more validation script template

- .github/workflows/main.yml
- .github/workflows/typescript.yml
- core/lib/Cardano/Address/Internal.hs
- core/lib/Cardano/Address/Style/Shelley.hs
- jsapi/cardano-addresses-jsapi.cabal
- jsapi/lib/Cardano/Address/JSAPI/InspectAddress.hs
- jsapi/lib/Cardano/Address/JSAPI/Version.hs
- jsapi/shell.nix
- jsapi/src/cardano-addresses.ts
- jsapi/src/types.ts
- jsapi/test/api.test.ts
- nix/haskell.nix
- release.nix
GitHub actions workflow for testing the typescript and updating gh-pages docs.
> Add CI for cardano-addresses-jsapi

- ChangeLog.md
- README.md
- jsapi/README.md
- jsapi/package-lock.json
- jsapi/package.json
ADP-787
-> https://github.com/input-output-hk/cardano-addresses/tree/piotr/typescript-badge
Perhaps that would be nice to have too...
> Update badges for Linux, Windows and Typescript builds

- core/lib/Cardano/Mnemonic.hs
ADP-909
Adds NFData instances so that we can more easily derive NFData for types which include these types.
> Add NFData instances to Cardano.Mnemonic types

- nix/cardano-addresses-js.nix
- nix/pkgs.nix
- nix/sources.json
This includes https://github.com/ghcjs/ghcjs/commit/2da23efdeb02b0570fd0693ec1610287f785f042 and https://github.com/ghcjs/ghcjs/commit/e4cd4232a31f6371c761acd93853702f4c7ca74c to fix the duplicates in `rts.js`.
> Use latest ghcjs

- command-line/lib/Command/Key/Child.hs
- command-line/test/Command/Key/ChildSpec.hs
> adopt proper hrp prefixes for 1854H purpose for shelley style

- README.md
- command-line/lib/Command/Address/Inspect.hs
- core/lib/Cardano/Address/Style/Byron.hs
- core/lib/Cardano/Address/Style/Icarus.hs
- core/lib/Cardano/Address/Style/Shelley.hs
- core/test/golden/inspectsart_forum_devote_street_sure_rather_head_chuckle_guard_poverty_release_quote_oak_craft_enemy/golden
- core/test/golden/inspectschurn_shaft_spoon_second_erode_useless_thrive_burst_group_seed_element_sign_scrub_buffalo_jelly_grace_neck_useless/golden
- core/test/golden/inspectsdraft_ability_female_child_jump_maid_roof_hurt_below_live_topple_paper_exclude_ordinary_coach_churn_sunset_emerge_blame_ketchup_much/golden
- core/test/golden/inspectsexcess_behave_track_soul_table_wear_ocean_cash_stay_nature_item_turtle_palm_soccer_lunch_horror_start_stumble_month_panic_right_must_lock_dress/golden
- core/test/golden/inspectstest_child_burst_immense_armed_parrot_company_walk_dog/golden
- core/test/golden/inspectstest_walk_nut_penalty_hip_pave_soap_entry_language_right_filter_choice/golden
- jsapi/test/api.test.ts
[DDW-742](https://input-output.atlassian.net/browse/DDW-742)
> Add address type to inspect

- jsapi/src/types.ts
> add address_type to typescript interface

- .github/workflows/typescript.yml
- command-line/cardano-addresses-cli.cabal
- core/cardano-addresses.cabal
- jsbits/cardano-addresses-jsbits.cabal
> Post-release 3.7.0

- README.md
- command-line/lib/Command/Key/WalletId.hs
- core/lib/Cardano/Address/Derivation.hs
Correcting hashing algo and docs
> Introduce wallet use digest 160

- README.md
- command-line/lib/Command/Key/WalletId.hs
- command-line/lib/Options/Applicative/Script.hs
- command-line/test/Command/Key/WalletIdSpec.hs
- core/lib/Cardano/Address/Script.hs
- core/lib/Cardano/Address/Script/Parser.hs
- core/lib/Cardano/Address/Style/Shared.hs
- core/test/Cardano/Address/Script/ParserSpec.hs
- core/test/Cardano/Address/ScriptSpec.hs
ADP-1621
adding support for walletid calculation for multisig wallets
> Walletid support for shared wallets

- CODEOWNERS
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE
MBO repo preparation
https://input-output.atlassian.net/browse/ADP-2785
> mbo preparation

- core/lib/Cardano/Address/Style/Byron.hs
- core/lib/Cardano/Address/Style/Icarus.hs
recheck and revisit code usage docs for byron and icarus
> Boost byron icarus docs

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- ChangeLog.md
- README.md
- command-line/cardano-addresses-cli.cabal
- command-line/package.yaml
- command-line/schemas/address-inspect.json
- core/cardano-addresses.cabal
- core/package.yaml
- jsapi/README.md
- jsapi/cardano-addresses-jsapi.cabal
- jsapi/package.json
- jsapi/src/index.ts
- jsbits/cardano-addresses-jsbits.cabal
- jsbits/package.yaml
https://github.com/IntersectMBO/cardano-addresses/issues/232
> Update GH pages and other things

- jsapi/src/cardano-addresses.ts
> Fix references in `src/cardano-addresses.d.ts`

- .github/workflows/main.yml
I hope this is all that's needed to publish pages.
> Add write permissions to pages

- command-line/lib/Command/Address/Inspect.hs
- core/lib/Cardano/Address/Script.hs
- jsapi/lib/Cardano/Address/JSAPI/InspectAddress.hs
- jsapi/lib/Cardano/Address/JSAPI/Version.hs
This pull request adds minimal changes required to make https://github.com/cardano-foundation/cardano-wallet/pull/4396 work.
> Minimal updates required for downstream `cardano-wallet`

- .dockerignore
- .gitignore
- Dockerfile
- README.md
- core/test/Cardano/Address/Style/ShelleySpec.hs
- justfile
This PR fixes building docker image.
```
$ just clean-build-docker
$ docker images 
-- one should see cardano-address image
$ docker run --rm cardano-address recovery-phrase generate --size 15
-- this should work now
```
> Docker fix 

- cardano-addresses.cabal
> Fix maintainer address
