IntersectMBO/cardano-addresses

.editorconfig
.github/workflows/main.yml
.hlint.yaml
.stylish-haskell.yaml
src/Cardano/Mnemonic.hs
stack.yaml
test/Cardano/MnemonicSpec.hs

- 6a2b7f18a8ad03d3489c943680c0664db1f61fd0
:round_pushpin: **use same cardano-crypto revision as the cardano-1.9.3 stack snapshot**
- 1f90c719d85f0605461ae8d69f5c9861bc3092dd
:round_pushpin: **use stack.yaml md5 as a cache key to force cache invalidation when deps change**
- 919da04ef0d2b1e0782b9fcd344c481d56938720
:round_pushpin: **add missing dot files (linter & editor config)**
- 7857036e7b4148e9255c869e86a1e2ad0583a144
:round_pushpin: **documentation and naming adjustements to make the module more digestable**

Documentation adjustments

---

src/Cardano/Address.hs
src/Cardano/Address/Derivation.hs
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
src/Cardano/Codec/Cbor.hs
test/Cardano/Address/Style/IcarusSpec.hs

- 4ae694ee10e25a4860537bd432cb5ded78b87c39
:round_pushpin: **move 'NetworkDiscriminant' down to the term level**
There's no need to have this as a type-level constraint here. It is just adding unecessary complexity
- 8aa7abc3299f91c2bb87e6d1260c059f7b1cebcc
:round_pushpin: **re-locate and rename/split 'addressToText' to 'base58' and 'bech32'**
- e77ecaa351b09f935ada68ed6f6b03bf9ad87234
:round_pushpin: **simplify extensions' set for 'Cardano.Address.Derivation'**

Module adjustments / simplifications

---

src/Cardano/Address.hs
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
src/Cardano/Codec/Cbor.hs
src/Cardano/Mnemonic.hs
test/Cardano/Codec/CborSpec.hs
test/Cardano/MnemonicSpec.hs

- 21fb4567c2a591c34624c97471bddc43589f2658
:round_pushpin: **revise module export hierarchy in Cardano.Mnemonic**
Put the most useful stuff on the top, and the more internal ones on the bottom.
- e6a373c9f93211f2122a9e1f21de88469c50642a
:round_pushpin: **hide the internal constructor for 'Address'**
This only adds noise and may encourage people to construct their own address from
scratch. So, we only publicly expose an opaque 'Address' type and keep the internals
hidden. Still, a careful and curious reader looking at the source may decide to do
otherwise, which is fine.
- 9189c7e6a2477ad4cd0e32a90307b3ee6638cdc8
:round_pushpin: **have function for doing address encoding / decoding inside 'Cardano.Address'**
I had to remove some circular dependencies with Cardano.Codec.Cbor in order to do …

First documentation adjustments:

---

src/Cardano/Address/Style/Byron.hs
test/Cardano/AddressSpec.hs
test/Test/Arbitrary.hs

- d83d74894ced10f04674a4e5d2599158986f3fb6
:round_pushpin: **add roundtrip tests for address encoding/decoding**
When failing, the intermediate address is shown, as well as the
decoded output.
```
Falsified (after 1 test):
Byron {getKey = XPub {xpubPublicKey = "\DC2\149\ENQ\SUB\238s\237\158\156\DC1\ar\EMAli\200\&9.=&\232\GS84\157\216;\173\192\227\STX", xpubChaincode = ChainCode "o\ENQl\185?e\133z\RSb\149\135y>\147\133\237Z\252\187\157W\ENQ8\200:\t\141\196oo\170"}, derivationPath = (Index {getIndex = 2296535368},Index {getIndex = 2550258752}), payloadPassphrase = <scrubbed-bytes>}
RequiresMagic (ProtocolMagic {getProtocolMagic = 1})
Address KjgoiXJS2coNC8fv21Q2gVfjMdSjyWifXkLV64yHrqCrxH83hnoXCw3K5SsATzfZn5aQ1ZQ5tNYrp4YfB8eSUbD53sb7WivYoFej49X5Kyeb
↳ …
```

add roundtrip tests for address encoding/decoding

---

.hlint.yaml
src/Cardano/Address.hs
src/Cardano/Address/Derivation.hs
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
test/Cardano/Address/DerivationSpec.hs
test/Cardano/Address/Style/ByronSpec.hs
test/Cardano/Address/Style/IcarusSpec.hs
test/Cardano/AddressSpec.hs
test/Cardano/Codec/CborSpec.hs
test/Test/Arbitrary.hs

- 25857dbfa1b93b28203de29b065d2282d9725838
:round_pushpin: **provide thin wrapper on top of crypto primitives**
The cardano-crypto is quite 'old' and has a lot of legacy inherited from past decision. One of them
was the decision of keeping every key 'XPrv' encrypted in-memory which has been said useless by our
cryptographers quite a few times.
It is necessary to encrypt the key when storing it into a more persistent location, but this isn't a
concern for this library. We can therefore simplify quite a few interfaces by removing the question
of encryption passphrases altogether.
Another annoyance of 'cardano-crypto' is that it internally stores and represent XPrv as a combination of:
prv <> pub <> cc, and all conversion functions are made to and from this internal representation.
This is …

cardano-crypto wrapper

---

package.yaml
src/Cardano/Address.hs
src/Cardano/Address/Derivation.hs
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
test/Cardano/Address/DerivationSpec.hs
test/Cardano/Address/Style/ByronSpec.hs
test/Cardano/Address/Style/IcarusSpec.hs
test/Cardano/AddressSpec.hs
test/Cardano/Codec/CborSpec.hs
test/Test/Arbitrary.hs

- 28586e73647dc5b2c10a987984761c23f9bae6bd
:round_pushpin: **rework internals for 'Byron' and 'Icarus' to promote high-level interface more**
This creats more consistency between both modules, and also makes for more maintainable code in the long-run. Instead of exposing and using internal functions
(even in testing), we can rely on the defined abstractions that we are also going to present users of the library.
- 4f13154c705862b0abb63aee1f4e4db782bb91aa
:round_pushpin: **another round of revision on the documentation for 'Byron' and 'Icarus' styles**
- Added some clear depreciation notice on 'Byron'
- Some examples of using 'GenMasterKey', 'HardDerivation' and 'PaymentAddress'
- Hide some internal type or constructs.
- ab2d8612581e189ddb23ca13e79dbcdffa5cbc18
:round_pushpin: **cleanup …

Rework documentation and public interfaces for 'Cardano.Address.Style.*'

---

src/Cardano/Address.hs
src/Cardano/Address/Derivation.hs
src/Cardano/Address/Style/Shelley.hs

This makes the API a bit clearer about what key is what. In the end, users needs not to know that the staking key is located at the same path in the derivation tree.

distinguish between staking key and address key

---

src/Cardano/Address/Derivation.hs
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
src/Cardano/Address/Style/Jormungandr.hs
src/Cardano/Address/Style/Shelley.hs
test/Cardano/Address/DerivationSpec.hs

Before, modules would look quite empty unless one noticed the instance declaration below the main type. Now, the documentation is a lot clearer and gives less cryptic signatures for the various interfaces. For example:

re-export specialized function from Cardano.Address for better documentation

---

.hlint.yaml
README.md
cardano-addresses.cabal
package.yaml
src/Cardano/Address/Style/Byron.hs
src/Cardano/Address/Style/Icarus.hs
src/Cardano/Address/Style/Jormungandr.hs
src/Cardano/Address/Style/Shelley.hs
src/Command.hs
src/Command/Address.hs
src/Command/Address/Bootstrap.hs
src/Command/Address/Delegation.hs
src/Command/Address/Inspect.hs
src/Command/Address/Payment.hs
src/Command/Address/Pointer.hs
src/Command/Key.hs
src/Command/Key/FromRecoveryPhrase.hs
src/Command/Key/Inspect.hs
src/Options/Applicative/Derivation.hs
src/Options/Applicative/Discrimination.hs
src/Options/Applicative/MnemonicSize.hs
src/Options/Applicative/Style.hs
src/System/IO/Extra.hs
test/Command/Address/InspectSpec.hs

- 0c4e5bcce52c6d746db29aa3d3043eb1a38f65df
:round_pushpin: **return structured JSON instead of pretty string for address introspection**
So that the output can be easily parsed and used by another software.
TODO: `key inspect` as well for consistency.

`inspect` commands return structured JSON

---

.github/workflows/main.yml
.github/workflows/windows.yml
app/Main.hs
cardano-addresses.cabal
package.yaml
src/Command.hs
src/Options/Applicative/Discrimination.hs
test/Cardano/Address/Style/ByronSpec.hs
test/Command/Address/BootstrapSpec.hs
test/Command/Address/PaymentSpec.hs

- b7ac636ea8738fe86e0836f90f946efefe6b1cf3
:round_pushpin: **use pre-define 'hashFiles' function for cache**
- 9d633beaea9f63a486ac8c751ebf35fc622349db
:round_pushpin: **add workflow for Windows**
- d824f16fb34edb00cec24adf65091312821f38f4
:round_pushpin: **force UTF-8 encoding, with Windows tricks**
- 3df6364cec050ee1ce7c5f2e3432952b18bb3637
:round_pushpin: **do not spit back malformed network tag when given gibberish**
It's usually not a good idea to spit back to users something that we failed to parse in the first place. Instead, we should print what we would have expected.
- 598c7c8536d79e7cb0b3fd93919ed925a0490347
:round_pushpin: **remove unused pragma (new HLint is better at catching those)**

Windows Issues / Testing

---

src/Cardano/Address/Style/Shelley.hs
test/Command/Address/InspectSpec.hs

- f41c20106a3e917ec1707d6a2867860a033d8aea
:round_pushpin: **expect 32-byte script hash in addresses**
There has been a little quirk that made it to the final ledger implementation. Script hashes ended up being 32-byte digests instead of 28-byte like the rest. That is unfortunate and this commits deals with that.
- ce5a8ffa9b9acd2cb1da079df582c39de7848d15
:round_pushpin: **add regression test showing that addresses with 28-byte long script hashes can't be inspected correctly**

32-byte digest for script hashes

---

command-line/lib/Options/Applicative/MnemonicSize.hs
command-line/test/Command/RecoveryPhrase/GenerateSpec.hs

#52 
This PR increases the default mnemonic phrase length from **15 words** to **24 words**.

Increase default mnemonic phrase length.

---

command-line/test/Command/Address/InspectSpec.hs
core/lib/Cardano/Address/Style/Shelley.hs

Allow to inspect reward accounts wrt #46

---

command-line/cardano-addresses-cli.cabal
command-line/lib/Command/Address.hs
command-line/lib/Command/Address/Reward.hs
command-line/package.yaml
command-line/test/Command/Address/RewardSpec.hs
core/lib/Cardano/Address.hs
core/lib/Cardano/Address/Style/Shelley.hs

Based on https://github.com/input-output-hk/cardano-addresses/pull/56
*TODO:*
Built with:

Allow to generate stake addresses

---

command-line/test/Command/Address/InspectSpec.hs

wrt https://github.com/input-output-hk/cardano-addresses/issues/46
- f0073a1001b36bea35c1d0037c6f738d55e8bcf6
Additional inspect tests with cardano-cli generated stake and payment addrs

Additional inspect tests with cardano-cli generated stake and payment addrs

---

README.md
command-line/lib/Command/Address/Payment.hs
command-line/lib/Command/Address/Reward.hs

I have updated readme and cmdline exmples to include changes for generating `addr_test` and `stake_test1` addresses.
- 437d470e5577c934ad4eec2a7d591a04e3fa4881
Fix readme examples
- 7efc9244dc0dd39610f2fb77aa0a8c2e8f05d03f
Update cmd-line examples

Readme and example updates for addr_test and stake_test

---

cabal.project
stack.yaml

Relates to [ADP-428](https://jira.iohk.io/browse/ADP-428).
Ensures that RDRAND can never be the sole source of RNG entropy.
To generate mnemonics it goes through cryptonite `Crypto.Random.Entropy.getEntropy`.
Disabling the RDRAND backend will leave just the WinCryptoAPI (windows) and DevRandom, DevURandom backends (not windows).

Completely disable RDRAND in cryptonite using a cabal flag

---

command-line/lib/Command/Address/Delegation.hs
command-line/lib/Command/Address/Pointer.hs
command-line/test/Command/Address/DelegationSpec.hs
command-line/test/Command/Address/PointerSpec.hs
core/lib/Cardano/Address/Style/Shelley.hs

Before that, we would default to 'addr' prefix, even for testnet addresses.

infer bech32 prefix from base address for pointer & delegation

---

.github/workflows/windows.yml
command-line/cardano-addresses-cli.cabal
command-line/lib/Command/Address/Bootstrap.hs
command-line/lib/Command/Address/Inspect.hs
command-line/lib/Options/Applicative/Derivation.hs
command-line/package.yaml
command-line/test/Command/Address/BootstrapSpec.hs
command-line/test/Command/Address/InspectSpec.hs
command-line/test/Test/Utils.hs
core/lib/Cardano/Address/Errors.hs
core/lib/Cardano/Address/Style/Byron.hs
core/lib/Cardano/Address/Style/Shelley.hs
schemas/address-inspect.json
stack.yaml

This introduces a new option '--root', which, when provided, attempts
to decrypt the derivation path payload of Byron addresses in the
'inspect' command.
The commit also revise the 'bootstrap' command to be more consistent
with other commands, in particular:
- In 'bootstrap', the path is now given as an optional argument
(instead of an optional option).
- In 'bootstrap', the root public key is now passed as an optional
option (instead of an optional argument).
---
```
$ cat root.pub
xpub18amv7cs8kj0mxpk0l3vk2w6g22vyf7y5texr9huevqg9kd3davgv5j52xrfcf90kxx2zdrrl826pzc2kptgwegzzzpfgddwqkrk2gpc80hdq2
$ cat addr.pub
xpub1kvz64d7yggggk5uc8kf8t8jjmh3djlx7ksr2xu25na5ypjzjs59j8ym5gqga8un7yg8e6et6sex8kx0cejwjtz8gh8pj0zg7kc53nuq4x3xaw
$ cardano-address address bootstrap --root $(cat root.pub) …
```

allow decrypting derivation path of random addresses in 'inspect'

---

core/lib/Cardano/Address/Derivation.hs
core/lib/Cardano/Address/Style/Byron.hs
core/lib/Cardano/Address/Style/Icarus.hs
core/lib/Cardano/Address/Style/Jormungandr.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/test/Cardano/Address/Style/IcarusSpec.hs
core/test/Cardano/Address/Style/JormungandrSpec.hs
core/test/Cardano/Address/Style/ShelleySpec.hs
core/test/Test/Arbitrary.hs

Issue number #72 
I renamed `AccountingStyle` to `Role` and extended it by `Stake` (for Jormungandr), and also by `Multisig` (for Shelley), also extended `Depth` by `MultisigK` and used those to implement `deriveMultisigPrivateKey` and `deriveMultisigPublicKey`. The existing test in ShelleySpec checks : 
```
N(CKDpriv((kpar, cpar), i)) === CKDpub(N(kpar, cpar), i)
``` 
Moreover, I introduced separate Role for Icarus, Shelley and Jormungandr and adjusted the corresponding code accordingly.
Removed `StakingDerivation` interface

Derivation of multisig keys

---

command-line/lib/Command/Address/Bootstrap.hs
command-line/test/Command/Address/InspectSpec.hs
core/lib/Cardano/Address/Style/Shelley.hs
schemas/address-inspect.json

Embargo is still on, but this has been fixed on the node's side already

turn back script hashes as 28 bytes.

---

README.md
command-line/lib/Command/Address/Bootstrap.hs
command-line/lib/Command/Address/Delegation.hs
command-line/lib/Command/Address/Inspect.hs
command-line/lib/Command/Address/Payment.hs
command-line/lib/Command/Address/Reward.hs
command-line/lib/Options/Applicative/Discrimination.hs
command-line/test/Command/Address/BootstrapSpec.hs
command-line/test/Command/Address/PaymentSpec.hs

```console
$ cardano-address address bootstrap --help                                                                                                     ±[●][KtorZ/nicer--network-tag]
Those addresses, now deprecated, were used during the Byron era.
Usage: cardano-address address bootstrap [--root XPUB] --network-tag NETWORK-TAG
[DERIVATION-PATH]
Create a bootstrap address
Available options:
-h,--help                Show this help text
--root XPUB              A root public key. Needed for Byron addresses only.
--network-tag NETWORK-TAG
A tag which identifies a Cardano network.
┌ Byron / Icarus ──────────
│ 
│ mainnet
│ staging
│ testnet
...or alternatively, an explicit network tag as an integer.
DERIVATION-PATH          Slash-separated derivation path. Hardened indexes are
marked with a …
```

allow '--network-tag' to also accept pre-defined keywords: mainnet, staging, testnet.

---

command-line/cardano-addresses-cli.cabal
command-line/package.yaml
command-line/schemas/address-inspect.json
command-line/test/Command/Address/InspectSpec.hs

../ directories are not allowed and will most likely be
parse errors (for both cabal and stack) in the near future.

Fix extra-source-files in cardano-addresses-cli.cabal

---

command-line/lib/Command/Key/Hash.hs
command-line/test/Command/Key/HashSpec.hs

Just caught this while testing something else and got bitten by the "impossible: pattern-match not coverage all cases.". Obviously, test cases for this very particular thing were missing so I can only blame it on myself :upside_down_face:

fix missing pattern-match in the key hash command.

---

README.md
command-line/lib/Command/Key/Hash.hs
command-line/test/Command/Key/HashSpec.hs
command-line/test/Command/ScriptSpec.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Script/Parser.hs
core/test/Cardano/Address/ScriptSpec.hs

- 25e199d5b8dc2e6b233556980b06761476032283
:round_pushpin: **improve parsing error for 'Script' FromJSON instance**
And in particular, run the validation also in the JSON parser. I've added a few negative test scenarios to show what errors look like.
- c4b9db9a8debd3882509dd82888efa8b1ea69e81
:round_pushpin: **make 'keyHashFromText' works from key, extended keys and key hashes seamlessly.**
This also impacts the command-line parser and the JSON parser to have the same behavior.

Improve Script parser errors and support for key parsing 

---

.github/workflows/main.yml
ChangeLog.md
command-line/cardano-addresses-cli.cabal
command-line/lib/System/Git/TH.hs
command-line/package.yaml
core/cardano-addresses.cabal
core/package.yaml

ADP-552
Fixes problems found during the cardano-wallet v2020-11-17 release.
1. Fixes the `cardano-address --version` output, and bump to 3.1.1.
2. The `GITREV` environment variable can be used at build time to set the git version info, in case this program is not being built from a git clone.
3. Add a CI check to ensure that cabal files are up-to-date with respect to the hpack source.
Note that the CI pipeline is currently broken because github removed a function - the failure is not caused by this PR. I have built it locally.

Fix cabal package versions and bump to 3.1.1

---

core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Script/Parser.hs
core/test/Cardano/Address/Script/ParserSpec.hs
core/test/Cardano/Address/ScriptSpec.hs

I have extended script to account for ActiveFromSlot and ActiveUntilSlot. I have updated all functions engaged, json instance, json generator, and script parser. also added script parser tests.
I have tested the correctness of resultant scriptHash in cardano-wallet tests -> https://github.com/input-output-hk/cardano-wallet/pull/2401

Extend script by timelocks

---

command-line/lib/Command/Address/Bootstrap.hs

- c8a866ad96636688b3504464d5aef98effb8873a
Fix `cardano-address address bootstrap` example in cmd help
Before:
```
$ cat root.prv \
| cardano-address key child 14H/42H | tee addr.prv \
| cardano-address key public --with-chain-code \
| cardano-address address bootstrap --root $(cat root.prv | cardano-address key public) \
--network-tag testnet 14H/42H
Usage: cardano-address key public (--without-chain-code | --with-chain-code)
Get the public counterpart of a private key
Available options:
-h,--help                Show this help text
The private key is read from stdin.To get extended public key pass '--with-chain-code'.To get public key pass '--without-chain-code'.
option --root: Bech32 error: string has no separator char
Usage: cardano-address address bootstrap [--root XPUB] --network-tag …
```

Fix `cardano-address address bootstrap` example in cmd help

---

command-line/test/Command/Address/InspectSpec.hs
core/lib/Cardano/Codec/Cbor.hs

- 835ba729b21302c616eb3ec02f3a4001a6fce150
:round_pushpin: **add missing crc32 integrity check when decoding Byron/Icarus addresses.**

add missing crc32 integrity check when decoding Byron/Icarus addresses.

---

command-line/cardano-addresses-cli.cabal
command-line/package.yaml
command-line/test/Command/Address/InspectSpec.hs
command-line/test/Test/Utils.hs
core/cardano-addresses.cabal
core/package.yaml
ghcjs/build.sh
ghcjs/crc32.js
ghcjs/crypto-cbits.post.js
ghcjs/crypto-cbits.pre.js
ghcjs/crypto-wrappers.js
nix/haskell.nix
nix/sources.json

ADP-787
This uses the PR input-output-hk/haskell.nix#1064 and makes a working ghcjs build.
emcc is the emscriten C to JS compiler used to by ghcjs when running hsc2hs because so that constants in C code compiled with emcc will match constants in the code generated by ghcjs.
```screen
$ nix-build release.nix -A ghcjs.cardano-address.x86_64-linux
$ node result/bin/cardano-address.jsexe/all.js
Usage: all.js ((-v|--version) | COMMAND)
Command-line for address and key manipulation in Cardano.
...
$ nix-build release.nix -A ghcjs.haskellPackages.cardano-addresses.checks.unit.x86_64-linux
```
[Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-addresses-pr-108#tabs-jobs)

Update haskell.nix to get latest ghcjs emcc fixes

---

.gitattributes
core/cardano-addresses.cabal
core/package.yaml
core/test/Cardano/Address/ScriptSpec.hs
core/test/Cardano/Address/Style/ShelleySpec.hs
core/test/golden/art_forum_devote_street_sure_rather_head_chuckle_guard_poverty_release_quote_oak_craft_enemy/actual
core/test/golden/art_forum_devote_street_sure_rather_head_chuckle_guard_poverty_release_quote_oak_craft_enemy/golden
core/test/golden/churn_shaft_spoon_second_erode_useless_thrive_burst_group_seed_element_sign_scrub_buffalo_jelly_grace_neck_useless/actual
core/test/golden/churn_shaft_spoon_second_erode_useless_thrive_burst_group_seed_element_sign_scrub_buffalo_jelly_grace_neck_useless/golden
core/test/golden/draft_ability_female_child_jump_maid_roof_hurt_below_live_topple_paper_exclude_ordinary_coach_churn_sunset_emerge_blame_ketchup_much/actual
core/test/golden/draft_ability_female_child_jump_maid_roof_hurt_below_live_topple_paper_exclude_ordinary_coach_churn_sunset_emerge_blame_ketchup_much/golden
core/test/golden/excess_behave_track_soul_table_wear_ocean_cash_stay_nature_item_turtle_palm_soccer_lunch_horror_start_stumble_month_panic_right_must_lock_dress/actual
core/test/golden/excess_behave_track_soul_table_wear_ocean_cash_stay_nature_item_turtle_palm_soccer_lunch_horror_start_stumble_month_panic_right_must_lock_dress/golden
core/test/golden/test_child_burst_immense_armed_parrot_company_walk_dog/actual
core/test/golden/test_child_burst_immense_armed_parrot_company_walk_dog/golden
core/test/golden/test_walk_nut_penalty_hip_pave_soap_entry_language_right_filter_choice/actual
core/test/golden/test_walk_nut_penalty_hip_pave_soap_entry_language_right_filter_choice/golden
stack.yaml

This PR is in preparation for https://github.com/input-output-hk/cardano-addresses/pull/110 because fixing the `addr` prefix to read the network ID changes quite a bit of this data, and editing the Haskell file directly invokes dreams of a solitary hermit hut where a cast iron pan is the most recent technological advancement.
I added `pretty-simple` to format the output in a nice way, otherwise it'd be all on one line and impossible to diff.
I also fixed a test failure I got on the current master when freshly cloning regarding the json error. Maybe the CI will bail on that, we'll see.

ADP-744 golden tests for ShelleySpec

---

.github/workflows/main.yml
nix/stack-shell.nix
test/e2e/.gitignore
test/e2e/.rspec
test/e2e/Gemfile
test/e2e/Gemfile.lock
test/e2e/README.md
test/e2e/helpers/matchers.rb
test/e2e/spec/examples_spec.rb
test/e2e/spec/spec_helper.rb

**Motivation:** https://github.com/input-output-hk/cardano-addresses/pull/119#issuecomment-816455977
**Context:**
Every now and then we encounter that CLI example printed by `cardano-address` is out of date and needs to be fixed (like https://github.com/input-output-hk/cardano-addresses/pull/119). I thought it might be good idea to test those examples in kind of end-to-end fashion. This little test suite gets all the examples from the CLI and runs them making sure each command succeeds. 
**Output:**
```
$ rspec
CLI examples
cardano-address address payment
cardano-address address bootstrap
cardano-address address stake
cardano-address address delegation
cardano-address address pointer
cardano-address script
cardano-address key
Finished in 0.15025 seconds (files took 0.22205 seconds to …
```

Add tests against CLI examples printed by cardano-addresses

---

cabal.project
command-line/cardano-addresses-cli.cabal
command-line/exe/Main.hs
command-line/package.yaml
command-line/test/Main.hs
core/cardano-addresses.cabal
core/lib/Cardano/Address/Compat.hs
core/package.yaml
core/test/Main.hs
nix/haskell.nix

This prevents the `cabal` from attempting to build the package inside the nix shell (instead the version provided by the nix shell will be used).
This prevents errors like:
```
[nix-shell:~/iohk/cardano-addresses]$ js-unknown-ghcjs-cabal run cardano-addresses:test:unit
Warning: don't know how to find change monitoring files for the installed
package databases for ghcjs
Warning: Requested index-state 2021-03-23T15:14:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-03-23T15:08:40Z).
Resolving dependencies...
Build profile: -w ghcjs-8.10.4 -O1
In order, the following will be built (use -v for more details):
- cardano-addresses-jsbits-3.3.0 (lib) (first run)
- cardano-addresses-3.3.0 (lib) (configuration changed)
- cardano-addresses-3.3.0 (test:unit) (configuration …
```

Move jsbits from cabal.project to nix cabalProjectLocal

---

ChangeLog.md
command-line/cardano-addresses-cli.cabal
command-line/package.yaml
command-line/test/Command/Address/InspectSpec.hs
core/cardano-addresses.cabal
core/lib/Cardano/Address.hs
core/lib/Cardano/Address/Style/Byron.hs
core/lib/Cardano/Address/Style/Icarus.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/package.yaml
jsbits/cardano-addresses-jsbits.cabal
jsbits/package.yaml

ADP-847
This doesn't change behaviour, but augments existing APIs with checked-exceptions variants.
Additionally, a record type is added for the `eitherInspectAddress` result value. There were some refactors necessary to accommodate this. The existing `inspectAddress` still produces a JSON value however.
The only API change is the error type constuctors.
This should hopefully help and/or unblock @luite's work on the javascript wrapper.

Better error handling for inspectAddress

---

cabal.project
command-line/test/Test/Utils.hs
jsbits/emscripten/crypto-wrappers.js
nix/haskell.nix
nix/pkgs.nix
nix/sources.json
release.nix

Update ghc and ghcjs to 8.10.x.
This should fix the windows cross build and let us drop ghc-8.6.5 support.
[Hydra jobset](https://hydra.iohk.io/jobset/Cardano/cardano-addresses-pr-127)

Update to GHC 8.10

---

command-line/lib/Options/Applicative/Discrimination.hs
core/cardano-addresses.cabal
core/lib/Cardano/Address.hs
core/lib/Cardano/Address/Derivation.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Style/Byron.hs
core/lib/Cardano/Codec/Cbor.hs
stack.yaml

Updates the stack/CI build to use LTS Haskell 17.12 (ghc-8.10.4) and address warning messages from GHC.

Silence new warnings from GHC 8.10

---

.github/workflows/main.yml

It seems it is deprecated (https://github.com/input-output-hk/cardano-addresses/runs/2911314075?check_suite_focus=true).
I'm not sure if we need it at all so removing all together.
If needed, then can be replaced by something like `TAG_PREFIX_REGEX: [a-z-]*` as per https://github.com/anton-yurchenko/git-release#configuration.

remove deprecated ALLOW_TAG_PREFIX from release workflow

---

core/cardano-addresses.cabal
core/lib/Cardano/Address/Style/Shelley.hs
core/package.yaml

Looks like exporting of `ReferenceInfo` was forgotten.
Bumped up the version too.

Export `ReferenceInfo`

---

command-line/test/Command/Address/InspectSpec.hs

Adding few more tests for inspecting address type. Not covered types are: 1,2,3,5... I'm not sure if `payment address from script hash` is correctly identified as type 7.

More assertions against addres_type in address inspect

---

Dockerfile

I was unable to compile this project via docker by following the steps in the readme due to the `jsbits` dir not being accessible from the container.
Later on, after fixing that issue, I was also unable to run the project inside docker due to the lack of `libstdc++`. This fixed both of the issues for me.

Fixing Docker build. Fixes #137

---

README.md
command-line/cardano-addresses-cli.cabal
command-line/lib/Command/Key.hs
command-line/lib/Command/Key/Hash.hs
command-line/lib/Command/Key/WalletId.hs
command-line/lib/Options/Applicative/Format.hs
command-line/test/Command/Key/WalletIdSpec.hs

ADP-1359
Two things were done.
1. It was added "key walletid" that works on EXTENDED root and account keys, both private and public, to get wallet id.
A number of tests were added.
2. Optional flag "--hex" was added to "key hash" command. If used, then instead of bech32-encoded output user gets hex-encoded one.

Introduce wallet id in cli and add hex-encoded option to hashing of keys 

---

ChangeLog.md
command-line/cardano-addresses-cli.cabal
command-line/lib/Command/Key/WalletId.hs
command-line/package.yaml
core/cardano-addresses.cabal
core/package.yaml
jsapi/cardano-addresses-jsapi.cabal
jsapi/package-lock.json
jsapi/package.json
jsbits/cardano-addresses-jsbits.cabal
jsbits/package.yaml

- Bump the cardano-addresses version for a new release.
- Add release notes
- Improve the text of `cardano-address key walletid --help`

Bump version from 3.7.0 to 3.8.0

---

.github/workflows/windows.yml

Seeing this in Windows builds (https://github.com/input-output-hk/cardano-addresses/runs/5154477094?check_suite_focus=true)
```
checking package integrity...
error: mingw-w64-x86_64-mpfr: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
:: File /var/cache/pacman/pkg/mingw-w64-x86_64-mpfr-4.1.0-3-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
```
Trying to apply some workarounds:
- https://github.com/msys2/MSYS2-packages/issues/2343
- https://stackoverflow.com/questions/68669920/invalid-pgp-signature-when-updating-packages-in-msys2-despite-fixes
_(don't really know what I'm doing)_

Attempt to fix windows build

---

README.md
command-line/lib/Command/Key/Child.hs
command-line/lib/Command/Key/Hash.hs
command-line/lib/Command/Key/Inspect.hs
command-line/lib/Command/Key/Public.hs
command-line/test/Command/Key/ChildSpec.hs
command-line/test/Command/Key/HashSpec.hs
command-line/test/Command/Key/InspectSpec.hs
core/lib/Cardano/Address/Derivation.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/lib/Cardano/Codec/Bech32/Prefixes.hs
core/test/Cardano/Address/ScriptSpec.hs

1. Adding support for policy key derivation
4. Adding support in key hashes via role
5. policy key prefixes 
6. command line : support for 3 segment, public key and hash
7. docs update 
In line with https://github.com/cardano-foundation/CIPs/tree/master/CIP-1855 
(except policy_sk as we use _xsk throught the codebase)
@piotr-iohk @rvl would be good to have those changes before next release 3.9.0

Add policy key support

---

command-line/lib/Command/Key/WalletId.hs

Before:
```
A wallet ID is a 40-digit hexadecimal string derived from the wallet’s key. It is used by the cardano-wallet server to refer to specific wallets.
For shelley wallets the key can be either an extended root key (full multi-account wallets), or an extended account key (single-account wallets).
In the latter case either private or public extended key is accepted-- they will have the same wallet ID.
The bech32-encoded key is read from standard input.
In case of a shared-wallet the wallet id is calculated based onboth private (public) extended account key, payment template script andstaking template script. Each signature in any template script is denotedby cosigner#number
```
After:
```
A wallet ID is a 40-digit hexadecimal string derived from the wallet’s key. It is used by the …
```

Polish key walletid help message

---

.github/workflows/haskell.yml
cabal.project
command-line/cardano-addresses-cli.cabal
core/cardano-addresses.cabal
core/lib/Cardano/Address/Script.hs
core/package.yaml
jsbits/cardano-addresses-jsbits.cabal
stack.yaml

Make it possible to compile with both versions of `aeson` so downstream projects can be on whatever they need.
This change is meant to be temporary.  A full upgrade to `aeson-2` would occur when all downstream projects have completed their migration.

Aeson 1 & 2 compatibility

---

.github/workflows/windows.yml
core/lib/Cardano/Address/Style/Shared.hs
core/test/Cardano/Address/ScriptSpec.hs
core/test/Cardano/Address/Style/SharedSpec.hs

ADP-1623
Allowing to derive payment address, both private and public, for both UTxOInternal and UTxOExternal. It is needed in multisig work in cardano-wallet

Extend payment share key derivation

---

README.md
command-line/lib/Command/Address/Delegation.hs
command-line/lib/Command/Address/Payment.hs
command-line/lib/Command/Address/Pointer.hs
command-line/lib/Command/Address/Reward.hs
command-line/lib/Options/Applicative/Credential.hs
command-line/lib/Options/Applicative/Derivation.hs
command-line/test/Command/Address/DelegationSpec.hs
command-line/test/Command/Address/PaymentSpec.hs
command-line/test/Command/Address/RewardSpec.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/test/Cardano/Address/Style/ShelleySpec.hs

[ADP-1985](https://input-output.atlassian.net/browse/ADP-1985)
PR extends possible bech32 prefixes possible for key hashes, now also non shared ones also.
Also `Credential` is extended and can be constructed from key hash, for both payment and delegation credential.
`PaymentFromKeyHash` and `DelegationFromKeyHash` were added. Thanks to that payment and base address, as well as reward address now can be constructed from key hashes. The new functionality was checked on golden tests. Also proper support in command lines was added, along with testing and documentation.

Enable using key hashes

---

README.md
command-line/lib/Command/Address/Delegation.hs
command-line/lib/Command/Address/Payment.hs
command-line/lib/Command/Address/Reward.hs
command-line/lib/Options/Applicative/Credential.hs
command-line/lib/Options/Applicative/Derivation.hs
command-line/test/Command/Address/DelegationSpec.hs
command-line/test/Command/Address/PaymentSpec.hs
core/lib/Cardano/Address/Derivation.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/test/Cardano/Address/Style/ShelleySpec.hs

https://input-output.atlassian.net/browse/ADP-2114
The PR extends address construction for payment/delegation/reward addresses by adding credential via:
- script
- non-extended key
This is on top of extended key, key hash, script hash (and from pointer for delegation credential).
The functionalities are also supported in CLI. The tests are added, docs revisited and extended

Enable using script and pub keys in credentials

---

ChangeLog.md
command-line/lib/Command/Address/Bootstrap.hs
command-line/lib/Options/Applicative/Discrimination.hs
core/lib/Cardano/Address/Style/Byron.hs
core/lib/Cardano/Address/Style/Icarus.hs
core/test/Test/Arbitrary.hs

After this we have:
```
$ cardano-address address bootstrap
Those addresses, now deprecated, were used during the Byron era.
Usage: cardano-address address bootstrap [--root XPUB] --network-tag NETWORK-TAG
[DERIVATION-PATH]
Create a bootstrap address
Available options:
-h,--help                Show this help text
--root XPUB              A root public key. Needed for Byron addresses only.
--network-tag NETWORK-TAG
A tag which identifies a Cardano network.
┌ Byron / Icarus ──────────
│ 
│ mainnet
│ staging
│ testnet
│ preview
│ preprod
```
```
$ cardano-address address payment
Payment addresses carry no delegation rights whatsoever.
Usage: cardano-address address payment --network-tag NETWORK-TAG [SCRIPT]
Create a payment address
Available options:
-h,--help                Show this help …
```

Add support for preview and preprod

---

core/lib/Cardano/Address/Script.hs
core/test/Cardano/Address/ScriptSpec.hs

this is part of ADP-2379. `KeyRole` was extended and `Unknown` data constructor was added. And the needed code adjusted. The change is motivated by the fact that there are situations where for a given wallet we cannot state whether a given key hash is acting as Policy/Payment/Delegation, it is external for this wallet and unknown. The keys can be represented as bytes and only upon constructing value of type KeyHash we are assuming the role. In order to handle the situation where the key hash is unknown we introduced the Unknown role. In that case we will assume hex-encoded representation - in contrast to bech32 where we the role is known.
https://input-output.atlassian.net/browse/ADP-2312

Add Unknown key role and adjust code needed

---

core/lib/Cardano/Mnemonic.hs
core/test/Cardano/MnemonicSpec.hs

This PR updates several links to the `cardano-wallet` repository, which is now located at https://github.com/cardano-foundation/cardano-wallet.

Update links to `cardano-wallet` repository.

---

command-line/cardano-addresses-cli.cabal
command-line/test/Main.hs
nix/haskell.nix

This ensure we force the rigth codepages on windows to support utf8 caracters in the haskell source for the tests.

Fix windows utf-8 issues

---

.github/workflows/haskell.yml

I really think we don't want to run tests for that.

Drop GHC 9.2.8 from the GHA matrix

---

CODEOWNERS
CONTRIBUTING.md

This pull request defines [roles and responsibilities][1] for this repository, following the [Project management policy](https://input-output-hk.github.io/cardano-engineering-handbook/policy/project/index.html#project-management) of the [Cardano Engineering Handbook](https://input-output-hk.github.io/cardano-engineering-handbook/).
For the Haskell components, the @cardano-foundation is willing to take responsibility; I have written down corresponding names.
For the CI and JavaScript parts, @intersectmbo will have to be responsible. I have put down some tentative names there, but please feel free to change them.
[1]: https://input-output-hk.github.io/cardano-engineering-handbook/policy/project/index.html#roles-and-responsibilities

Define Roles and Responsibilities

---

ChangeLog.md
README.md
cabal.project
command-line/lib/Command/Key/Child.hs
command-line/lib/Command/Key/Hash.hs
command-line/lib/Command/Key/Inspect.hs
command-line/lib/Command/Key/Public.hs
command-line/lib/Command/Script/Hash.hs
command-line/test/Command/Key/ChildSpec.hs
command-line/test/Command/Key/HashSpec.hs
command-line/test/Command/Key/InspectSpec.hs
command-line/test/Command/Script/HashSpec.hs
command-line/test/Command/Script/PreimageSpec.hs
command-line/test/Command/Script/ValidationSpec.hs
core/lib/Cardano/Address/Script.hs
core/lib/Cardano/Address/Style/Shelley.hs
core/test/Cardano/Address/ScriptSpec.hs
core/test/Cardano/Address/Style/ShelleySpec.hs

This PR builds on top of the previous one and adds support of CIP 0105 to CLI. In particular the following was added:
1. Support of derivation of all varieties of `drep`, `cc_cold` and `cc_hot` keys, namely extended signing keys, extended verification key and verification keys. 
```
cardano-address key child 1852H/1815H/0H/5/0 < root.xsk > hot.xsk
cardano-address key public --with-chain-code < hot.xsk > hot.xvk
cardano-address key public --without-chain-code < hot.xsk > hot.vk
```
2. Support of making hash from verification keys (both varieties):
```
cardano-address key hash < hot.xvk > hot
cardano-address key hash < hot.vk > hot
```
3. Support for using `drep`, `cc_cold` and `cc_hot` keys, namely extended verification key and verification keys, and verification key hashes in scripts and …

CIP 0105 CLI support

---

core/test/Cardano/Address/Style/ShelleySpec.hs

I added golden tests for base16 values as specified here https://github.com/cardano-foundation/CIPs/tree/master/CIP-0105 (with the proposed correction here https://github.com/cardano-foundation/CIPs/pull/861)

CIP 0105 golden test for hex values 

---

ChangeLog.md
core/lib/Cardano/Address/Style/Shelley.hs
jsapi/test/api.test.ts

I would expect that inspecting a reward account address would use the `infoStakeScriptHash` field of `AddressInfo`, but it is using `infoScriptHash`. The pubkey version is using `infoStakeKeyHash` so this seems like a bug. I ran the tests both before and after the change, and all tests pass; they don't seem to cover this.
If this is the intended behavior, feel free to close this PR.

FIX: Inspecting reward accounts uses wrong `AddressInfo` field for staking scripts

---

ChangeLog.md
README.md
command-line/cardano-addresses-cli.cabal
command-line/lib/Command/Key.hs
command-line/lib/Command/Key/Private.hs
command-line/lib/Options/Applicative/Private.hs
command-line/test/Command/Key/PrivateSpec.hs
core/lib/Cardano/Codec/Bech32/Prefixes.hs
core/test/Cardano/Address/Style/ShelleySpec.hs

This PR enables to decompose ANY extended signing key `*_xsk` into signing key and chain code.
New cli command was added which operate as follows:
```
$ cat drep.xsk
drep_xsk1vpdsm49smzmdwhd4kjmm2mdyljjysm746rafjr7r8kgfanj849psw8pfm305g59wng0akw3qzppmfh6k5z7gx66h2vppu022m4eqaj26rh6d7en9tf9fu52hmysjzuacaxfmfya65h8jmddrclwf3kxl8snfs3eg
$ cardano-address key private --signing-key < drep.xsk
drep_sk1vpdsm49smzmdwhd4kjmm2mdyljjysm746rafjr7r8kgfanj849psw8pfm305g59wng0akw3qzppmfh6k5z7gx66h2vppu022m4eqajg5xmwma
$ cardano-address key private --signing-key --hex < drep.xsk
605b0dd4b0d8b6d75db5b4b7b56da4fca4486fd5d0fa990fc33d909ece47a943071c29dc5f4450ae9a1fdb3a201043b4df56a0bc836b5753021e3d4add720ec9
$ cardano-address key private --chain-code < drep.xsk …
```

Support signing keys

---

cabal.project
core/cardano-addresses.cabal
flake.lock
flake.nix
nix/haskell.nix

Uses the `repo` branch in hackage-overlay-ghcjs created manually using https://github.com/input-output-hk/hackage-overlay-ghcjs/pull/6

Use foliage hackage overlay ghcjs

---

cabal.project
command-line/cardano-addresses-cli.cabal
command-line/test/Test/Utils.hs

Remove dependency on hjsonschema

---

cabal.project
cardano-addresses.cabal
flake.lock

* put bounds on cardano-crypto dependency: we set the bound in such a way both CHaP and Hackage can provide a valid version
* replace cryptonite with crypton
#294

Prepare publication to hackage

---

cabal.project
cardano-addresses.cabal

As of this commit, version 1.3.0 of cardano-crypto has been published to https://hackage.haskell.org/. This version is identical to version 1.2.0 which is published to https://chap.intersectmbo.org, so it's fine to leave the option to the end-user to use one or the other repository.
We keep the CHaP configuration in the `cabal.project` with updated indices as it can be useful for contributors and provides a reference with "pinned" versions for building in CI, but as it's not published to the package repository, it won't affect build plan downstream which will use whatever local configuration.

Tweak cabal configuration to support CHaP and Hackage
